CREATE TABLE [dbo].[AppSalt]
(
	[Id] INT NOT NULL IDENTITY,
	SaltValue VARCHAR(100) NOT NULL,
	UserId INT NOT NULL
	CONSTRAINT [PK_Salt] PRIMARY KEY ([Id]),
	CONSTRAINT FK_Salt_User FOREIGN KEY (UserId) REFERENCES AppUser(Id)

)