CREATE TABLE [dbo].[AppUser]
(
	[Id] INT NOT NULL IDENTITY,
	Email VARCHAR(50) NOT NULL,
	Passwd VARBINARY(64) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	RoleId INT NOT NULL DEFAULT (1),
	NickName VARCHAR(50) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT (1), 
    [Created] DATETIME2 NOT NULL 
	CONSTRAINT [PK_User] PRIMARY KEY ([Id]),	
    CONSTRAINT [UQ_User_Email] UNIQUE (Email),
	CONSTRAINT FK_Role_User FOREIGN KEY (RoleId) REFERENCES AppRole(Id)
)